web: daphne -b 0.0.0.0 -p $PORT config.asgi:application
worker: celery -A config.celery worker -l info --concurrency=2
beat: celery -A config.celery beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
