# Generated by Django 5.2.15 on 2026-06-25 02:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('payments', '0001_initial'),
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionCredit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.IntegerField(default=0, help_text='Solde actuel du crédit commission. Peut être temporairement négatif si commission déduite en cours de course.', verbose_name='Solde (XOF)')),
                ('total_topups', models.PositiveIntegerField(default=0, verbose_name='Total rechargé (XOF)')),
                ('total_commissions', models.PositiveIntegerField(default=0, verbose_name='Total commissions déduites (XOF)')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission_credit', to='drivers.driver')),
            ],
            options={
                'verbose_name': 'Crédit commission',
                'verbose_name_plural': 'Crédits commission',
                'db_table': 'commission_credits',
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tx_type', models.CharField(choices=[('topup', 'Rechargement'), ('commission', 'Commission course'), ('refund', 'Remboursement'), ('adjustment', 'Ajustement admin'), ('cancellation_fee', "Frais d'annulation")], max_length=20)),
                ('amount', models.IntegerField(help_text='Positif = crédit, négatif = débit', verbose_name='Montant (XOF)')),
                ('balance_before', models.IntegerField(verbose_name='Solde avant')),
                ('balance_after', models.IntegerField(verbose_name='Solde après')),
                ('provider_name', models.CharField(blank=True, max_length=50)),
                ('provider_tx_id', models.CharField(blank=True, max_length=100)),
                ('adjustment_reason', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('adjusted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_adjustments', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='drivers.driver')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='payments.payment')),
                ('ride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='rides.ride')),
            ],
            options={
                'verbose_name': 'Transaction crédit',
                'db_table': 'credit_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['driver'], name='credit_tran_driver__109789_idx'), models.Index(fields=['tx_type'], name='credit_tran_tx_type_4ff4f8_idx'), models.Index(fields=['ride'], name='credit_tran_ride_id_d1dde3_idx')],
            },
        ),
    ]
