# Generated by Django 5.2.15 on 2026-06-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_withdrawal_reference'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='withdrawal',
            new_name='withdrawals_status_ddef8f_idx',
            old_name='withdrawals_status_idx',
        ),
        migrations.RenameIndex(
            model_name='withdrawal',
            new_name='withdrawals_driver__f5d7f8_idx',
            old_name='withdrawals_driver_idx',
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='tx_type',
            field=models.CharField(choices=[('topup', 'Rechargement'), ('commission', 'Commission course'), ('refund', 'Remboursement'), ('adjustment', 'Ajustement admin'), ('cancellation_fee', "Frais d'annulation"), ('withdrawal_hold', 'Retrait en attente'), ('withdrawal_release', 'Retrait annulé (recrédité)'), ('withdrawal_completed', 'Retrait effectué')], max_length=20),
        ),
    ]
