# Generated by Django 5.2.15 on 2026-06-25 02:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False, verbose_name='Provider principal')),
                ('api_base_url', models.URLField(blank=True, max_length=500)),
                ('api_key_enc', models.TextField(blank=True, verbose_name='Clé API (chiffrée)')),
                ('api_secret_enc', models.TextField(blank=True, verbose_name='Secret API (chiffré)')),
                ('sender_id', models.CharField(blank=True, default='MoveBissau', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('cost_per_sms', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Coût estimé par SMS (USD)')),
            ],
            options={
                'verbose_name': 'Provider SMS',
                'db_table': 'sms_providers',
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField()),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='general', help_text='Pour regrouper dans le dashboard : general, pricing, matching, commission, cancellation, rating', max_length=50, verbose_name='Catégorie')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration système',
                'verbose_name_plural': 'Configurations système',
                'db_table': 'system_config',
            },
        ),
    ]
