# Generated by Django 5.2.15 on 2026-06-25 02:57

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pickup_location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('pickup_address', models.CharField(blank=True, max_length=500)),
                ('dropoff_location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('dropoff_address', models.CharField(blank=True, max_length=500)),
                ('estimated_distance_m', models.PositiveIntegerField(verbose_name='Distance estimée (m)')),
                ('suggested_price', models.PositiveIntegerField(verbose_name='Prix indicatif (XOF)')),
                ('proposed_price', models.PositiveIntegerField(verbose_name='Prix proposé par le passager (XOF)')),
                ('vehicle_type', models.CharField(choices=[('moto', 'Moto-taxi'), ('car', 'Voiture')], max_length=10)),
                ('search_radius_m', models.PositiveIntegerField(verbose_name='Rayon de recherche (m)')),
                ('max_drivers_notified', models.PositiveIntegerField(verbose_name='Max chauffeurs notifiés')),
                ('notified_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('offers_received', 'Offres reçues'), ('accepted', 'Acceptée'), ('expired', 'Expirée'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de course',
                'verbose_name_plural': 'Demandes de course',
                'db_table': 'ride_requests',
            },
        ),
        migrations.CreateModel(
            name='RideOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offered_price', models.PositiveIntegerField(verbose_name='Prix proposé par le chauffeur (XOF)')),
                ('is_counter_offer', models.BooleanField(default=False, verbose_name='Est une contre-offre')),
                ('driver_distance_m', models.PositiveIntegerField(blank=True, null=True, verbose_name='Distance chauffeur → passager (m)')),
                ('estimated_arrival_s', models.PositiveIntegerField(blank=True, null=True, verbose_name="Temps d'arrivée estimé (s)")),
                ('driver_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Rejetée'), ('expired', 'Expirée'), ('withdrawn', 'Retirée')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_offers', to='drivers.driver')),
                ('ride_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='rides.riderequest')),
            ],
            options={
                'verbose_name': 'Offre de course',
                'verbose_name_plural': 'Offres de course',
                'db_table': 'ride_offers',
            },
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pickup_location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('pickup_address', models.CharField(blank=True, max_length=500)),
                ('dropoff_location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('dropoff_address', models.CharField(blank=True, max_length=500)),
                ('actual_route', django.contrib.gis.db.models.fields.LineStringField(blank=True, geography=True, null=True, srid=4326)),
                ('agreed_price', models.PositiveIntegerField(verbose_name='Prix convenu (XOF)')),
                ('actual_distance_m', models.PositiveIntegerField(blank=True, null=True, verbose_name='Distance réelle (m)')),
                ('commission_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Commission (XOF)')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=15.0, max_digits=5, verbose_name='Taux de commission (%)')),
                ('vehicle_type', models.CharField(choices=[('moto', 'Moto-taxi'), ('car', 'Voiture')], max_length=10)),
                ('status', models.CharField(choices=[('driver_assigned', 'Chauffeur assigné'), ('driver_en_route', 'Chauffeur en route'), ('driver_arrived', 'Chauffeur arrivé'), ('passenger_onboard', 'Passager à bord'), ('completed', 'Terminée'), ('paid', 'Payée'), ('cancelled', 'Annulée')], default='driver_assigned', max_length=25)),
                ('driver_assigned_at', models.DateTimeField(auto_now_add=True)),
                ('driver_en_route_at', models.DateTimeField(blank=True, null=True)),
                ('driver_arrived_at', models.DateTimeField(blank=True, null=True)),
                ('passenger_onboard_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.CharField(blank=True, choices=[('passenger', 'Passager'), ('driver', 'Chauffeur'), ('system', 'Système')], max_length=10, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancellation_fee', models.PositiveIntegerField(default=0, verbose_name="Frais d'annulation (XOF)")),
                ('share_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('share_expires_at', models.DateTimeField(blank=True, null=True)),
                ('emergency_triggered', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='drivers.driver')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides_as_passenger', to=settings.AUTH_USER_MODEL)),
                ('ride_offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ride', to='rides.rideoffer')),
                ('ride_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ride', to='rides.riderequest')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'rides',
            },
        ),
        migrations.AddIndex(
            model_name='riderequest',
            index=models.Index(fields=['status'], name='ride_reques_status_27ae98_idx'),
        ),
        migrations.AddIndex(
            model_name='riderequest',
            index=models.Index(fields=['passenger'], name='ride_reques_passeng_20b60f_idx'),
        ),
        migrations.AddIndex(
            model_name='rideoffer',
            index=models.Index(fields=['ride_request'], name='ride_offers_ride_re_a1bf8b_idx'),
        ),
        migrations.AddIndex(
            model_name='rideoffer',
            index=models.Index(fields=['driver'], name='ride_offers_driver__1da1bf_idx'),
        ),
        migrations.AddIndex(
            model_name='rideoffer',
            index=models.Index(fields=['status'], name='ride_offers_status_d6827a_idx'),
        ),
        migrations.AddConstraint(
            model_name='rideoffer',
            constraint=models.UniqueConstraint(fields=('ride_request', 'driver'), name='unique_offer_per_driver_per_request'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['passenger'], name='rides_passeng_2390e2_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['driver'], name='rides_driver__8fdcf2_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['status'], name='rides_status_376a74_idx'),
        ),
    ]
