# Generated by Django 5.2.15 on 2026-06-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='luggage_type',
            field=models.CharField(choices=[('none', 'Aucun bagage'), ('small', 'Petit sac'), ('suitcase', 'Valise'), ('large', 'Gros bagage')], default='none', max_length=10),
        ),
    ]
