# Generated by Django 5.2.15 on 2026-07-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_luggage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Réduction promo (XOF)'),
        ),
        migrations.AddField(
            model_name='ride',
            name='promo_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='promo_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
