# Generated by Django 5.2.15 on 2026-07-01 23:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_ride_discount_amount_ride_promo_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RideMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=500)),
                ('message_key', models.CharField(blank=True, help_text='Clé du message prédéfini (vide = texte libre)', max_length=40)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rides.ride')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message de course',
                'db_table': 'ride_messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['ride', 'created_at'], name='ride_messag_ride_id_0f868d_idx')],
            },
        ),
    ]
