# Generated by Django 5.2.15 on 2026-06-25 02:57

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident_type', models.CharField(choices=[('sos_emergency', 'Urgence SOS'), ('dispute', 'Litige'), ('driver_behavior', 'Comportement chauffeur'), ('passenger_behavior', 'Comportement passager'), ('accident', 'Accident'), ('payment_issue', 'Problème paiement'), ('other', 'Autre')], max_length=30)),
                ('description', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('investigating', 'En investigation'), ('resolved', 'Résolu'), ('closed', 'Fermé')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('critical', 'Critique')], default='medium', max_length=10)),
                ('resolution', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_assigned', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents_reported', to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='rides.ride')),
            ],
            options={
                'verbose_name': 'Incident',
                'db_table': 'incidents',
                'indexes': [models.Index(fields=['status'], name='incidents_status_9db31b_idx'), models.Index(fields=['ride'], name='incidents_ride_id_5cfc09_idx')],
            },
        ),
    ]
