# Generated by Django 5.2.15 on 2026-06-25 02:57

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_type', models.CharField(choices=[('moto', 'Moto-taxi'), ('car', 'Voiture')], max_length=10)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('is_verified', models.BooleanField(default=False, verbose_name='Documents validés')),
                ('is_online', models.BooleanField(default=False, verbose_name='En ligne')),
                ('verification_status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_rides', models.PositiveIntegerField(default=0)),
                ('acceptance_rate', models.DecimalField(decimal_places=2, default=100.0, max_digits=5, verbose_name="Taux d'acceptation (%)")),
                ('current_location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('location_updated_at', models.DateTimeField(blank=True, null=True)),
                ('cancellations_today', models.PositiveIntegerField(default=0)),
                ('forced_offline_until', models.DateTimeField(blank=True, null=True, verbose_name="Mis hors ligne jusqu'à")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chauffeur',
                'verbose_name_plural': 'Chauffeurs',
                'db_table': 'drivers',
            },
        ),
        migrations.CreateModel(
            name='DriverDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('identity', "Pièce d'identité"), ('license', 'Permis de conduire'), ('insurance', 'Assurance'), ('criminal_record', 'Casier judiciaire'), ('vehicle_registration', 'Carte grise'), ('photo', 'Photo du véhicule')], max_length=30)),
                ('file_url', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='drivers.driver')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document chauffeur',
                'db_table': 'driver_documents',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_type', models.CharField(choices=[('moto', 'Moto'), ('car', 'Voiture')], max_length=10)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('plate_number', models.CharField(blank=True, max_length=20)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='drivers.driver')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'db_table': 'vehicles',
            },
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['is_online', 'is_verified'], name='drivers_is_onli_0ca9ff_idx'),
        ),
        migrations.AddIndex(
            model_name='driverdocument',
            index=models.Index(fields=['driver', 'doc_type'], name='driver_docu_driver__d01bf7_idx'),
        ),
    ]
