# Generated by Django 5.2.15 on 2026-06-29 11:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Pourcentage'), ('fixed', 'Montant fixe (XOF)')], max_length=10)),
                ('discount_value', models.PositiveIntegerField(help_text='Valeur (% ou XOF)')),
                ('max_discount', models.PositiveIntegerField(blank=True, help_text='Plafond de réduction (XOF) pour les pourcentages', null=True)),
                ('min_ride_price', models.PositiveIntegerField(default=0, help_text='Prix minimum de course')),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 = illimité')),
                ('max_uses_per_user', models.PositiveIntegerField(default=1)),
                ('current_uses', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Code promo',
                'db_table': 'promo_codes',
            },
        ),
        migrations.CreateModel(
            name='PromoUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_amount', models.PositiveIntegerField()),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='accounts.promocode')),
                ('ride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rides.ride')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Utilisation code promo',
                'db_table': 'promo_usages',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referral_code', models.CharField(db_index=True, max_length=10)),
                ('referrer_bonus', models.PositiveIntegerField(default=500, help_text='Bonus parrain (XOF)')),
                ('referred_bonus', models.PositiveIntegerField(default=500, help_text='Bonus filleul (XOF)')),
                ('referrer_credited', models.BooleanField(default=False)),
                ('referred_credited', models.BooleanField(default=False)),
                ('referred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parrainage',
                'db_table': 'referrals',
                'constraints': [models.UniqueConstraint(fields=('referred',), name='unique_referral_per_user')],
            },
        ),
    ]
