# Generated by Django 5.2.15 on 2026-07-01 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_promo_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_promo_codes', to=settings.AUTH_USER_MODEL),
        ),
    ]
