# Generated by Django 5.2.15 on 2026-06-25 02:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('provider_type', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('bank', 'Banque'), ('card', 'Carte bancaire')], max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('api_base_url', models.URLField(blank=True, max_length=500)),
                ('api_key_enc', models.TextField(blank=True, verbose_name='Clé API (chiffrée)')),
                ('api_secret_enc', models.TextField(blank=True, verbose_name='Secret API (chiffré)')),
                ('merchant_id', models.CharField(blank=True, max_length=100)),
                ('callback_url', models.URLField(blank=True, max_length=500)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('min_amount', models.PositiveIntegerField(default=100, verbose_name='Montant min (XOF)')),
                ('max_amount', models.PositiveIntegerField(default=500000, verbose_name='Montant max (XOF)')),
            ],
            options={
                'verbose_name': 'Provider de paiement',
                'db_table': 'payment_providers',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField(verbose_name='Montant total (XOF)')),
                ('commission_amount', models.PositiveIntegerField(verbose_name='Commission plateforme (XOF)')),
                ('driver_amount', models.PositiveIntegerField(verbose_name='Montant chauffeur (XOF)')),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('orange_money', 'Orange Money'), ('moov_money', 'Moov Money')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Complété'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20)),
                ('provider_tx_id', models.CharField(blank=True, max_length=100)),
                ('provider_name', models.CharField(blank=True, max_length=50)),
                ('provider_response', models.JSONField(blank=True, null=True)),
                ('cash_confirmed_by_driver', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to='drivers.driver')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rides.ride')),
            ],
            options={
                'verbose_name': 'Paiement',
                'db_table': 'payments',
                'indexes': [models.Index(fields=['ride'], name='payments_ride_id_38c783_idx'), models.Index(fields=['status'], name='payments_status_d621e5_idx')],
            },
        ),
    ]
