# Generated by Django 5.2.15 on 2026-06-25 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_refund_reference'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='refund',
            new_name='refunds_status_2569d8_idx',
            old_name='refunds_status_idx',
        ),
        migrations.RenameIndex(
            model_name='refund',
            new_name='refunds_reason_824f43_idx',
            old_name='refunds_reason_idx',
        ),
    ]
